### ISSUE TITLE
infinite http calls 

### ISSUE THREAD

**Issue by deeeed** [gabrielpoca/meteor-redux-demo#1]
I just tried to clone / run the project without any changes, but I can see that my client keeps sending infinite http requests:
<img width="797" alt="screen shot 2016-06-29 at 6 00 04 pm" src="https://cloud.githubusercontent.com/assets/4800095/16448306/596378ea-3e23-11e6-82b8-e4ae7d301794.png">
I suppose it is not the expected behavior ?

**Comment by gabrielpoca** [comment]
Hi @deeeed ! For a moment I was questioning my sanity because I knew I wasn't doing any HTTP call. And turns out it is not in the application code, the infinite requests happen because of the package `simple:dev-error-overlay`, I could remove it, but for the sake of this demo I don't think it will be a problem.
